### ISSUE TITLE
Issue with ng-repeat

### ISSUE THREAD

**Issue by naveenduttvyas** [garethwhittaker/angularjs-typed-effect#1]
Hi, When I am using ng-repeat on this, first item is OK but other iteration text is getting typed already, it doesnt wait till the turn comes up. how can we handle it?

**Comment by garethwhittaker** [comment]
Hi @naveenduttvyas,

There are a number of optional settings (including **delay**) that you can specify when using the directive. Here's an example of one possible implementation utilising `ng-repeat` :

**view**

``` html
<div ng-controller="MessagesCtrl as m">
    <p ng-repeat="message in m.messages" typed-effect text="message.text"
        delay="{{ message.delay }}" blink="{{ message.blink }}"></p>
</div>
```

**controller**

``` javascript
angular.module('myApp', [])
    .controller('MessagesCtrl', MessagesCtrl);

function MessagesCtrl() {
    this.messages = [
        {
            text: 'example message 1',
            delay: 0,
            blink: false
        },
        {
            text: 'example message 2',
            delay: 2000, // milliseconds
            blink: true
        }
    ];
}
```

**Comment by garethwhittaker** [comment]
I've added an optional **callback** setting in release **v1.1.0**

As an alternative to the solution above, you can now provide your own callback function to be triggered after typing has finished.

This should provide you with a lot more flexibility / control over sequencing.
